ALTER TABLE accounts 
  ADD COLUMN is_verified NOT NULL DEFAULT false
  ALTER COLUMN role SET NOT NULL
  ALTER COLUMN role SET DEFAULT "user"

CREATE TABLE email_confirmations (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  account_id INT REFERENCES accounts,
  created_at TIMESTAMPZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPZ NOT NULL
)